<?php
	include_once '../includes/config.php';
	
	if(!$session->isLoggedIn() || !isset($_POST['ajaxPageName']))	{
		header('Location:../login.php');
	}
	
	//This page is used to hold all the details about the user's Ajax methods.
	switch($_POST['ajaxPageName'])	{
		case 'prodItemReqStat':
			/*
			 * Page Name : production.php
			 * Event : Change on "Pending Productions" Select Box.
			 */
			//This is used to check whether the given item can be produced by the user.
			$prodItemId = $_POST['itemId'];
			$sql = "SELECT `item_name`, `req_item_qty`, `item_qty` 
				FROM (SELECT * FROM `{$db->name()}`.`{$db->table('require')}` WHERE `item_id` = '{$prodItemId}') as `temp_require`
				LEFT JOIN `{$db->name()}`.`{$db->table('inventory')}`
				ON `temp_require`.`req_item_id` = `{$db->table('inventory')}`.`item_id`
				LEFT JOIN `{$db->name()}`.`{$db->table('item')}`
				ON `temp_require`.`req_item_id` = `{$db->table('item')}`.`item_id`";
			$query = $db->query($sql);
			$itemStats = '<table class="type1">';
			$itemStats .= '<tr> <th class="name"> Item Name </th> <th class="time"> Required </th> <th class="time"> Inventor </th> </tr>';
			$canProduce = true;
			while($row = $db->result($query))	{
				if($row->item_qty == NULL)	{
					$row->item_qty = 0;
				}
				if ($row->item_qty >= $row->req_item_qty )	{
					$rowColor = 'green';
				} else {
					$rowColor = 'red';
					$canProduce = false;
				}
				$itemStats .= "<tr class=\"item_{$rowColor}\"><td class=\"name\">{$row->item_name}</td><td class=\"time\">{$row->req_item_qty}</td><td class=\"time\">{$row->item_qty}</td></tr>";
			}
			$itemStats .= '</table>';
			echo $itemStats;
			if($canProduce)	{
				echo '<a href="#" id="produceSelectedItem"> Produce Item </a>';
			} else {
				echo '<p class="message">You can\'t make that item. You require the items in Red.</p>';
			}
			break;
		case 'prodItemConfirm':
			/*
			 * Page Name : production.php
			 * Event : Click on "Produce Item" button generated by above AJAX script.
			 */
			//This is used to confirm whether the items can be produced or not. If yes then produce it.
			//We Check again just to make sure that there is not malfunction of the AJAX
			$prodItemId = $_POST['itemId'];
			$sql = "SELECT `req_item_id`, `req_item_qty`, `item_qty`
				FROM (SELECT * FROM `{$db->name()}`.`{$db->table('require')}` WHERE `item_id` = '{$prodItemId}') as `temp_require`
				LEFT OUTER JOIN `{$db->name()}`.`{$db->table('inventory')}`
				ON `temp_require`.`req_item_id` = `{$db->table('inventory')}`.`item_id`";
			$query = $db->query($sql);
			$itemReqList = '';
			while($row = $db->result($query))	{
				if($row->item_qty < $row->req_item_qty)	{
					echo 1;
					$db->freeResults($query);
					break;
				} else {
					$itemReqList["{$row->req_item_id}"] = intval($row->req_item_qty);
				}
			}
			$db->freeResults($query);
			//Now the user has all the items. Proceed to update the Users inventory.
			$userId = $session->getUserId();
			foreach($itemReqList as $itemId => $itemQty)	{
				$sql = "UPDATE `{$db->name()}`.`{$db->table('inventory')}` SET `item_qty` = `item_qty` - {$itemQty} WHERE `item_id` = '{$itemId}' AND `user_id` = '{$userId}'";
				$query = $db->query($sql);
				//This is the fail safe so that a revert of data is possible.
				if($query)	{
					$itemReqList["{$itemId}"] = -$itemReqList["{$itemId}"];
				} else {
					//TODO : Perform revert procedures and throw and error.
					echo '2';
					break;
				}
			}
			
			//Now we add the item to the production queue.
			$sql = "SELECT `item_make_time` FROM `{$db->name()}`.`{$db->table('item')}` WHERE `item_id` = '{$prodItemId}'";
			$query = $db->query($sql);
			$result = $db->result($query);
			$itemMakeTime = $result->item_make_time;
			$db->freeResults($query);
			
			$sql = "INSERT INTO `{$db->name()}`.`{$db->table('production')}` VALUES ('{$userId}', '{$prodItemId}', '{$itemMakeTime}')";
			$query = $db->query($sql);
			echo '0';
			break;
		case 'itemToSellQty':
			/*
			 * Page Name : sellItem.php
			 * Event : Change on "Choose an Item to Sell" select box.
			 */
			$userId = $session->getUserId();
			$itemId = $db->escapeString($_POST['itemId']);
			$sql = "SELECT `item_qty` FROM `{$db->name()}`.`{$db->table('inventory')}` WHERE `item_id` = '{$itemId}' AND `user_id` = '{$userId}'";
			$query = $db->query($sql);
			$result = $db->result($query);
			$db->freeResults($query);
			$itemQtyOptions = '';
			$result->item_qty = intval($result->item_qty);
			for($i = 1; $i <= $result->item_qty; $i++)	{
				$itemQtyOptions .= "<option value=\"{$i}\">{$i}</option>";
			}
			echo $itemQtyOptions;
			break;
		case 'itemToSellAuction':
			/*
			 * Page Name : sellItem.php
			 * Event : Click on "Add to Auction" Button.
			 */
			$userId = $session->getUserId();
			$itemId = $_POST['itemId'];
			$itemQty = intval($_POST['itemQty']);
			$startBid = $_POST['startBid'];
			$buyout = $_POST['buyout'];
			//First check the validity of the operation.
			$sql = "SELECT `item_qty` FROM `{$db->name()}`.`{$db->inventory}` WHERE `item_id` = '{$itemId}' AND `user_id` = '{$userId}'";
			$query = $db->query($sql);
			$result = $db->result($query);
			$db->freeResults($query);
			if($result->item_qty < $itemQty)	{
				echo '1';
				break;
			}
			//First we remove the item from the Users inventory.
			if($result->item_qty == $itemQty)	{
				$sql = "DELETE FROM `{$db->name()}`.`{$db->table('inventory')}` WHERE `user_id` = '{$userId}' AND `item_id` = '{$itemId}'";
			} else {
				$sql = "UPDATE `{$db->name()}`.`{$db->table('inventory')}` SET `item_qty` = `item_qty` - {$itemQty} WHERE `user_id` = '{$userId}' AND `item_id` = '{$itemId}'";
			}
			$query = $db->query($sql);
			if(!$query)	{
				echo '2';
				break;
			}
			//We post the auction.
			$sql = "INSERT INTO `{$db->name()}`.`{$db->table('auction')}` VALUES ('{$userId}', '{$itemId}', '{$startBid}', NULL, '{$buyout}', '{$itemQty}', '{DEFAULT_ACTION_TIME}')";
			$query = $db->query($sql);
			if($query)	{
				echo '0';
			} else {
				//Failure rollback.
				addItemToInventory($userId, $itemId, $itemQty);
				echo '2';
			}
			break;
		default:
			echo 'Invalid Page Name. Check your Code.';
	}
?>